name: '🐞 Bug report'
title: 'bug: '
description: 'Create a report to help us improve'
labels: [bug]
body:
  - type: checkboxes
    id: packages
    attributes:
      label: 'Affected Packages'
      description: 'Select every package affected by this bug'
      options:
        - label: 'Formi'
        - label: 'WienerTime'
        - label: '@yeger/debounce'
        - label: '@yeger/fol'
        - label: '@yeger/streams'
        - label: '@yeger/turbo-graph'
        - label: '@yeger/vitest-utils'
        - label: '@yeger/vue-masonry-wall'
        - label: 'd3-graph-controller'
        - label: 'key-hierarchy'
        - label: 'resumon'
        - label: 'vecti'
        - label: 'vue-fast-mount'
        - label: 'vue-marmoset-viewer'
  - type: textarea
    id: bug-description
    attributes:
      description: 'A clear and concise description of the bug.'
      label: 'Description'
      placeholder: 'Bug description'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      description: 'Please provide a link to a repository that can reproduce the problem you ran into. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "needs-reproduction" label. If no reproduction is provided we might close it.'
      label: 'Reproduction'
      placeholder: 'Reproduction'
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      description: 'If applicable, add any other context about the problem here.'
      label: 'Additional context'
  - type: checkboxes
    id: assign
    attributes:
      label: 'Preferences'
      description: 'Select everything that applies to you'
      options:
        - label: 'I want to be assigned to and work on this issue myself'
