name: '✨ Feature request'
title: 'feat: '
description: Suggest a feature for this project
labels: [enhancement]
body:
  - type: checkboxes
    id: packages
    attributes:
      label: 'Affected Packages'
      description: 'Select every package affected by this feature request'
      options:
        - label: '@yeger/eslint-config'
        - label: '@yeger/vue-masonry-wall'
        - label: '@yeger/vue2-masonry-wall'
        - label: 'vecti'
  - type: textarea
    id: feature-description
    attributes:
      description: 'A clear and concise description of the requested feature.'
      label: 'Description'
      placeholder: 'Feature description'
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      description: 'If applicable, add any other context about the feature here.'
      label: 'Additional context'
  - type: checkboxes
    id: assign
    attributes:
      label: 'Preferences'
      description: 'Select everything that applies to you'
      options:
        - label: 'I want to be assigned to and work on this issue myself'
