name: '✨ Feature request'
title: '[Feature]: '
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      description: 'A clear and concise description of what the problem is.'
      label: 'Description'
      placeholder: 'Feature description'
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      description: 'A clear and concise description of what you want to happen.'
      label: 'Solution'
      placeholder: 'Solution description'
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      description: 'If applicable, add any other context about the problem here.'
      label: 'Additional context'
  - type: checkboxes
    id: assign
    attributes:
      label: 'Preferences'
      description: 'Select everything that applies to you'
      options:
        - label: 'I want to be assigned to and work on this issue myself'
