
name: "ℹ️ Something else"
description: Something else
labels: [question]
body:
  - type: textarea
    id: issue-description
    attributes:
      description: "Describe your issue"
      label: Description
      placeholder: "A clear and concise description of what the problem is."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      description: "Describe the solution you'd like"
      label: Solution
      placeholder: "A clear and concise description of what you want to happen."
  - type: textarea
    id: additional
    attributes:
      description: "If applicable, add any other context about the problem here"
      label: "Additional context"
